import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { MainLayout } from "@/core/components/MainLayout";
import { QueryClientProvider } from "@/core/components/QueryClientProvider";
import { ErrorBoundary } from "@/core/components/ErrorBoundary";
import CartProvider from "@/modules/cart/provider/CartProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, "antialiased")}>
        <ErrorBoundary>
          <QueryClientProvider>
            <CartProvider>
              <MainLayout>{children}</MainLayout>
            </CartProvider>
          </QueryClientProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
